#!/bin/sh

sudo pacman -S enchant mythes-en ttf-liberation hunspell-en_US ttf-bitstream-vera \
               pkgstats adobe-source-sans-pro-fonts gst-plugins-good ttf-droid \
               ttf-dejavu aspell-en icedtea-web gst-libav ttf-ubuntu-font-family \
               ttf-anonymous-pro jre8-openjdk languagetool libmythes libreoffice-fresh \
               ntfs-3g btop htop vlc \
               vlc cheese nomacs ufw kdeconnect gimp thunderbird kdenlive thunar 

sudo ufw enable
sudo ufw status verbose
sudo systemctl enable ufw.service
